AWSTemplateFormatVersion: '2010-09-09'
Description: This template creates an S3Bucket.

Resources:
  Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: BucketOwnerFullControl

Outputs:
  S3Bucket:
    Value: !Ref Bucket
    Description: The name of the s3 bucket
